name: sample_work-on

on:
 push:
  branches:
   - master
   
jobs:
   wait:
     runs-on: ubuntu-latest
     steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cypress test
        uses: ./
        with:
         working-directory: examples/wait-on
         start: npm start
         wait-on: 'http://localhost:3050'
          
          
         
         
     
